### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by pyronicide** [dcos/dcos-website#708] opened 2016-05-11 15:48 UTC
We'd like to start posting to a DC/OS blog. Can we get one added to the website?

**Comment by ashenden** [comment] 2016-05-11 16:49
We can do this.  Before we do, can we get 100% buy-in from @williamsaaron and anyone else who'd have a strong opinion?  I say this because we will engage Awkward for this and eat into our retainer with them.  If this is a priority/need, I'm happy to push, but don't want to spend the $ if we're on the fence about it.

**Comment by williamsaaron** [comment] 2016-05-11 18:43
I fully support adding the blog.

There are a couple other very minor things I'd like us to rev by early June, primarily on the community page and home page, but they are lower priority. I'll create issues for them so we can plan them.

**Comment by ashenden** [comment] 2016-05-11 22:57
@kevinkalle before you guys start in on this, let's setup a meeting to talk through scope.

**Comment by williamsaaron** [comment] 2016-05-11 23:32
I'd like to participate in that conversation, but I know my schedule is a mess. Could we do it early Monday morning PT?

**Comment by kevinkalle** [comment] 2016-05-12 08:46
We are closed on Monday. Could you guys prepare a "briefing" that I can review and do the call later that week? I'm in favour of some existing framework instead of building a blog from scratch.

**Comment by ashenden** [comment] 2016-05-12 16:06
I'll setup a calendar invite for later next week.  We can save ourselves the briefing for now -- we're just looking for a basic blog (Posts, Categories, Search, Authors, etc...).  I'll sync with @pyronicide and @williamsaaron on management requirements.  If no CMS tools are needed, we could probably keep this even simpler.

**Comment by kevinkalle** [comment] 2016-05-12 17:28
Would something like this even be enough, this blog is completely static: https://awkward.co/blog.html

**Comment by ashenden** [comment] 2016-05-12 17:40
I think so.  @williamsaaron won't be joining our meeting next week.  He is in China (http://cl.ly/2J0f2G1J0K2a).  I'll get his thoughts in advance.  But, I imagine this is pretty close.

**Comment by williamsaaron** [comment] 2016-05-12 17:40
Seems reasonable as a starting point.

Things I would like that aren't there (but I think could be added and still be static):
- social links on every post to make it easy to share.
-  tags or categories (that get translated into SEO keywords).

**Comment by kevinkalle** [comment] 2016-05-12 20:04
This is a good enough starting point guys. We don't need anything else to get started. Adding this to our planning for next week. CHINA!

**Comment by pyronicide** [comment] 2016-05-12 21:07
I'd like to write some markdown and check it into `dcos-website`. No need for a CMS or anything like that.

**Comment by TimonVS** [comment] 2016-05-24 19:45
@williamsaaron @ashenden @pyronicide I made a PR for the blog (#712). Search and filtering by tags isn't working yet but the rest is done. You can preview the blog on `/posts/`.
I probably do need login info for Algolia to implement search.

**Comment by ashenden** [comment] 2016-05-24 20:51
Thanks @TimonVS.  Just pulled it down and it looks good.  I'm going to setup a call with @kevinkalle in the next day or two to run over it in person.  We'll file issues where it makes sense.

**Comment by kevinkalle** [comment] 2016-05-25 12:25
@daniellouwekooijmans did a review with John yesterday. The following items were discussedL

- Post should have social share options
- Height of all cells of same size should be the same
- Category labels should be clickable on blog home and posts
- Make category switch CTA more obvious
- Blog should live at /blog
- Line separating date and content needs spacing love
- Text line underline styling is unique to blog
- Truncate blog post titles at something reasonable for cells
- Cell layout on blog when less than 3 cells per row is odd
- Github star widget in header doesn't appear on Blog on retina screens

**Comment by daniellouwekooijmans** [comment] 2016-05-25 12:35
@TimonVS could you take a look at these tasks

- [ ] Height of all cells of same size should be the same
- [ ] Category labels should be clickable on blog home and posts
- [ ] Blog should live at /blog
- [ ] Github star widget in header doesn't appear on Blog on retina screens

I'll do the others:
- Post should have social share options
- Make category switch CTA more obvious
- Line separating date and content needs spacing love
- Text line underline styling is unique to blog
- Truncate blog post titles at something reasonable for cells
- Cell layout on blog when less than 3 cells per row is odd

**Comment by pyronicide** [comment] 2016-05-26 14:30
Is this in a state that we could make live? I'd like to have a page talking about the DC/OS Community sync next week that I can link folks to.

**Comment by ashenden** [comment] 2016-05-26 15:27
Until all the issues I outlined are fixed, I don't want us to launch.

Also, we need to go live with at least 3 blog posts so this section doesn't
look pathetic and empty.

—
*John Ashenden*

**Comment by daniellouwekooijmans** [comment] 2016-05-26 15:45
@ashenden could you clarify these points:

- Where should categories be clickable? In the detail view of a post? The post cards are now fully clickable so making the categories clickable means we have to change that.
- Which underlining differs from the rest of the site?
- We've truncated the blog titles in the smaller cells
- Cell layout adapts to fill out the space for the last post. In production this means you would only see this at the very bottom

**Comment by ashenden** [comment] 2016-05-26 16:26
For reference, these are all the open issues, complete with descriptions and screenshots (http://cl.ly/3P1l161j1r2n).  We're going to be turning off GH issues in the next week or so, so didn't want you to lose visibility.

Where should categories be clickable? In the detail view of a post? The post cards are now fully clickable so making the categories clickable means we have to change that.
* Wherever we display the category, it should be clickable.  Even in the post as full-click targets, the link should be clickable.

Which underline differs from the rest of the site?
* Referring to this (http://cl.ly/180N3y1K402u).  We don't really use this anywhere else on site.  Does it feel strange to use it here?

We've truncated the blog titles in the smaller cells
* Thanks.

Cell layout adapts to fill out the space for the last post. In production this means you would only see this at the very bottom
* Yes.  I'm suggesting we do not do this.  It looks strange and unintentional.

**Comment by TimonVS** [comment] 2016-06-06 11:50
@ashenden the blog should be ready. Could you check it out?

**Comment by williamsaaron** [comment] 2016-06-07 22:06
do we have a test / dev / staging site where I can see this, or do I need to build my own? I'd like to take a look and get it launched this week if we can.

**Comment by pyronicide** [comment] 2016-06-07 22:12
It should already be on `dev.dcos.io`. I ngrok it to you if that isn't
working.

**Comment by ashenden** [comment] 2016-06-08 00:06
@TimonVS i rebased `feature/blog` onto `master` and then committed back to `feature/blog`.  Looks like all checks are passing on your PR (https://github.com/dcos/dcos-website/pull/712).  However, when I try to run this branch locally, I get this error (http://cl.ly/25333X2V1f3B).  Hesitant to merge until I can confirm locally that it works.  Any advice on how to resolve this issue?

**Comment by pyronicide** [comment] 2016-06-08 00:39
Working for me. node v6.0.0

**Comment by TimonVS** [comment] 2016-06-08 08:36
@ashenden @pyronicide I'm running Node 5.10.0, so it should be working. @ashenden did you run `npm install`?

**Comment by ashenden** [comment] 2016-06-08 19:34
@TimonVS got the blog running locally after deleting my `/build` directory.  Merged it into `develop` however the build test is failing.  Just pulled down `develop` to my laptop, and getting an error on `npm start` (http://cl.ly/2v2J0Z0C2F1A)  could you look into this?

also, before we move the blog live, I would like to make sure we resolve these open issues — https://dcosjira.atlassian.net/browse/SITE-18?jql=project%20%3D%20SITE%20AND%20labels%20in%20(blog-launch)%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC

**Comment by TimonVS** [comment] 2016-06-10 12:07
@ashenden the overflow error is an OSX issue. It can be fixed by following this guide: http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit.

**Comment by ashenden** [comment] 2016-06-10 15:27
FIx worked.  Thanks.

Any idea why the build test on `develop` would be failing though?

**Closed** 2016-06-15 08:47 UTC
Labels: type/design, type/html, type/javascript
